name: Mos Diner
on:
  schedule:
    - cron: "30 12 * * 1-5"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: execute mensa.py
        run: |
          python mensa.py
        env:
          URL: "https://studentenwerk-marburg.de/essen-trinken/speisekarte"
          CANTEEN: "420"
          API: ${{ secrets.MOS_DINER }}
